### ISSUE TITLE
请问大佬，这个脚本支持M系列处理器吗？我在的m1pro本上执行后tableplus无法打开...

### ISSUE THREAD

**Issue by Oumuv** [marlkiller/dylib_dobby_hook#15]
![image](https://github.com/marlkiller/dylib_dobby_hook/assets/20614424/ee402e4b-01b9-4e9e-a85c-655c9f4c0004)

**Comment by marlkiller** [comment]
支持 arm

官网重新下载最新版
执行脚本后,用命令行启动看看
```
cd script
sudo sh auto_hack.sh
```

**Comment by Oumuv** [comment]
脚本执行后重启电脑就正常了，感谢大佬提供的脚步。膜拜~
