### ISSUE TITLE
tableplus Version 6.0.6 (558) 破解不能用了

### ISSUE THREAD

**Issue by nmweizi** [marlkiller/dylib_dobby_hook#16]
返回好像不是LicenseModel了

<img width="233" alt="image" src="https://github.com/marlkiller/dylib_dobby_hook/assets/1232444/b6dc5c90-d562-42da-bc78-694d34b25c75">

**Comment by miosx** [comment]
Objc改Swift了。
变复杂了一些。

**Comment by marlkiller** [comment]
有人编译后改版权, 发到各 个 Mac 软件下载站了, 所以这块被官方和谐了吧;
周末有空在看看如何 patch;

**Comment by miosx** [comment]
<img width="636" alt="image" src="https://github.com/marlkiller/dylib_dobby_hook/assets/131627176/ff2215e1-62e9-46dd-9c10-019bfe5413ae">
