### ISSUE TITLE
 请教一个libdobby.a 的编译问题

### ISSUE THREAD

**Issue by CoderShmily** [marlkiller/dylib_dobby_hook#17]
大佬，我在M2的机器，你这个demo可以正常编译。自己Xcode15.3新建了一个动态库工程，为什么总是编译失败，不管是用你的libdobby.a，还是dobby官方的github的release产物的arm64 arm64e universal 的.a或者libdobby.dylib 都报错。用你的libdobby.a是下边的错误，是你的工程设置了什么编译参数吗？  
![iShot_2024-06-14_15 17 42](https://github.com/marlkiller/dylib_dobby_hook/assets/13568251/3d46385d-3812-4fc0-ab03-1630ff7a4d3f)

**Comment by CoderShmily** [comment]
![iShot_2024-06-14_15 27 06](https://github.com/marlkiller/dylib_dobby_hook/assets/13568251/0a50a70f-38d0-4bb2-a232-7ced5c92d360)

**Comment by marlkiller** [comment]
![image](https://github.com/marlkiller/dylib_dobby_hook/assets/25897113/0514b026-d73e-4e5e-944c-d658081f8cc8)
![image](https://github.com/marlkiller/dylib_dobby_hook/assets/25897113/9e1f9b70-6551-46e6-a566-a84f8f8108cf)


试试这俩个配置, 还不行的话, 就挨个对比下配置吧;

**Comment by CoderShmily** [comment]
@marlkiller 谢大佬 是缺少libc++这个库，看原Dobby库也没说需要这个依赖，总算编译过了😭
