### ISSUE TITLE
MacOS上另一款比Table Plus更好用的Mysql client - Querious, 大佬得空试试看

### ISSUE THREAD

**Issue by NKU915** [marlkiller/dylib_dobby_hook#19]
Querious 
https://www.araelium.com/querious

**Comment by marlkiller** [comment]
only mysql 啊, 太短小了

**Comment by NKU915** [comment]
官网是这么说的：MySQL and compatible databases。正在做PostgreSQL的问卷，应该很快就会支持 PostgreSQL。
主要是UI太漂亮了

**Comment by marlkiller** [comment]
适用了下, mysql 8.x 似乎不支持... 
太拉了, 不如 tableplus, 已放弃;

**Comment by NKU915** [comment]
应该是支持的，之前有个3.2的TNT版都可以，但是macOS Sonoma就不能用了。4.x试用版本也是连8.0（我一直用mysql 8.0）。crack是很费时费力，有Table plus也够用，辛苦了

**Comment by TrialMacApp** [comment]
> Querious https://www.araelium.com/querious

https://github.com/TrialMacApp/TrialMacApp

**Comment by NKU915** [comment]
> > Querious https://www.araelium.com/querious
> 
> https://github.com/TrialMacApp/TrialMacApp

很不幸，我的Mac正好时Intel架构的CPU
>   - 只支持 arm 架构 m 系芯片
>   - Intel 用户可以直接关掉网页，未来也不支持 Intel 架构

**Comment by TrialMacApp** [comment]
> > > Querious https://www.araelium.com/querious
> > 
> > 
> > https://github.com/TrialMacApp/TrialMacApp
> 
> 很不幸，我的Mac正好时Intel架构的CPU
> 
> > * 只支持 arm 架构 m 系芯片
> > * Intel 用户可以直接关掉网页，未来也不支持 Intel 架构

做了编译支持，但是没有强制检测，根据readme使用吧

**Comment by NKU915** [comment]
> > > > Querious https://www.araelium.com/querious
> > > 
> > > 
> > > https://github.com/TrialMacApp/TrialMacApp
> > 
> > 
> > 很不幸，我的Mac正好时Intel架构的CPU
> > > * 只支持 arm 架构 m 系芯片
> > > * Intel 用户可以直接关掉网页，未来也不支持 Intel 架构
> 
> 做了编译支持，但是没有强制检测，根据readme使用吧

@TrialMacApp 非常感谢。
刚试了一下v4.0.14,赶紧破解不够彻底。登录时

**Comment by NKU915** [comment]
> > > > Querious https://www.araelium.com/querious
> > > 
> > > 
> > > https://github.com/TrialMacApp/TrialMacApp
> > 
> > 
> > 很不幸，我的Mac正好时Intel架构的CPU
> > > * 只支持 arm 架构 m 系芯片
> > > * Intel 用户可以直接关掉网页，未来也不支持 Intel 架构
> 
> 做了编译支持，但是没有强制检测，根据readme使用吧

@TrialMacApp 非常感谢。
刚试了一下v4.0.14, 感觉破解不够彻底。
打开应用时还是出现：
![CleanShot 2024-08-12 at 11 25 19@2x](https://github.com/user-attachments/assets/224fb1ca-ccb3-4af1-863e-4adc2c5f6131)

在界面上多停留一会儿，还是会出现：
<img width="319" alt="image" src="https://github.com/user-attachments/assets/a8ae97c5-7d06-4338-be1d-b982303633e8">

再过一段时间，应用还是会自动退出。
多谢

**Comment by NKU915** [comment]
激活是成功的：
![CleanShot 2024-08-12 at 11 34 14@2x](https://github.com/user-attachments/assets/3865a0fe-9d8a-4c9b-ac84-7ba4521f15b6)

**Comment by NKU915** [comment]
app.yaml中querious的版本是***4.0.13***，而我试用的是最新4.0.14版本。估计是版本的问题。@TrialMacApp 
```yaml
- all_version: 1
  app_store: 0
  arm: 1
  name: Querious
  path: ''
  remark: ''
  show_name: ''
  version: 4.0.13
  x86: 1
```

**Comment by TrialMacApp** [comment]
> app.yaml中querious的版本是_**4.0.13**_，而我试用的是最新4.0.14版本。估计是版本的问题。@TrialMacApp
> 
> ```yaml
> - all_version: 1
>   app_store: 0
>   arm: 1
>   name: Querious
>   path: ''
>   remark: ''
>   show_name: ''
>   version: 4.0.13
>   x86: 1
> ```

命令行试一下，我这最新版也没问题的。

**Comment by NKU915** [comment]
@TrialMacApp 命令行不支持Intel：
```shell
sudo ./TrialMacApp
sudo: unable to execute ./TrialMacApp: Bad CPU type in executable
```

GUI激活，虽然提示成功了，其实报错了：
```
do shell script "xattr -cr /Applications/Querious.app && cp /Users/...(隐去)/Querious/TrialMacApp.app/Contents/Frameworks/libTrialMacApp.dylib /Applications/Querious.app/Contents/Frameworks && /Users/...(隐去)/Querious/TrialMacApp.app/Contents/Resources/optool install -p /Applications/Querious.app/Contents/Frameworks/libTrialMacApp.dylib -t /Applications/Querious.app/Contents/MacOS/Querious && codesign -f -s - --all-architectures --deep /Applications/Querious.app" with administrator privileges
Error: {
    NSAppleScriptErrorAppName = TrialMacApp;
xattr: [Errno 1] Operation not permitted: '/Applications/Querious.app'";mitted: '/Applications/Querious.app/Contents/Frameworks/libTrialMacApp.dylib'
xattr: [Errno 1] Operation not permitted: '/Applications/Querious.app'";d: '/Applications/Querious.app/Contents/Frameworks/libTrialMacApp.dylib'
    NSAppleScriptErrorNumber = 1;
    NSAppleScriptErrorRange = "NSRange: {0, 522}";
```

**Comment by TrialMacApp** [comment]
> @TrialMacApp 命令行不支持Intel：
> 
> ```shell
> sudo ./TrialMacApp
> sudo: unable to execute ./TrialMacApp: Bad CPU type in executable
> ```
> 
> GUI激活，虽然提示成功了，其实报错了：
> 
> ```
> do shell script "xattr -cr /Applications/Querious.app && cp /Users/...(隐去)/Querious/TrialMacApp.app/Contents/Frameworks/libTrialMacApp.dylib /Applications/Querious.app/Contents/Frameworks && /Users/...(隐去)/Querious/TrialMacApp.app/Contents/Resources/optool install -p /Applications/Querious.app/Contents/Frameworks/libTrialMacApp.dylib -t /Applications/Querious.app/Contents/MacOS/Querious && codesign -f -s - --all-architectures --deep /Applications/Querious.app" with administrator privileges
> Error: {
>     NSAppleScriptErrorAppName = TrialMacApp;
> xattr: [Errno 1] Operation not permitted: '/Applications/Querious.app'";mitted: '/Applications/Querious.app/Contents/Frameworks/libTrialMacApp.dylib'
> xattr: [Errno 1] Operation not permitted: '/Applications/Querious.app'";d: '/Applications/Querious.app/Contents/Frameworks/libTrialMacApp.dylib'
>     NSAppleScriptErrorNumber = 1;
>     NSAppleScriptErrorRange = "NSRange: {0, 522}";
> ```

确实是，脚本没有执行交叉编译，现在可以试试

**Comment by NKU915** [comment]
> 确实是，脚本没有执行交叉编译，现在可以试试

@TrialMacApp 还是不行，具体是什么错误没有显示：
```
你的机器架构 【x86_64】
受支持的app如下:
【序号】-【名称               】-【版本      】-【ARM】-【X86】-【MAS】-【其他                   】
--------------------------------------------------------------------------------------------------
【1  】-【Macs Fan Control    】-【1.5.16    】-【是 】-【   】-【   】-【                       】
【2  】-【Things3             】-【all       】-【是 】-【是 】-【   】-【                       】
【3  】-【Xnip                】-【all       】-【是 】-【是 】-【是 】-【                       】
【4  】-【Transmit            】-【all       】-【是 】-【是 】-【是 】-【                       】
【5  】-【BuhoCleaner         】-【all       】-【是 】-【是 】-【   】-【                       】
【6  】-【Image2Icon          】-【2.18      】-【是 】-【   】-【是 】-【                       】
【7  】-【FileZilla Pro       】-【3.66.5    】-【是 】-【   】-【是 】-【                       】
【8  】-【menubarx            】-【all       】-【是 】-【是 】-【是 】-【                       】
【9  】-【SQLPro Studio       】-【all       】-【是 】-【是 】-【是 】-【                       】
【10 】-【Texifier            】-【1.9.27    】-【是 】-【   】-【   】-【                       】
【11 】-【Sketch              】-【all       】-【是 】-【是 】-【是 】-【                       】
【12 】-【Omi录屏专家         】-【all       】-【是 】-【是 】-【是 】-【                       】
【13 】-【CleanShot X         】-【4.7       】-【是 】-【   】-【   】-【                       】
【14 】-【Doppler             】-【all       】-【是 】-【是 】-【   】-【                       】
【15 】-【Text Scanner        】-【1.7.5     】-【是 】-【   】-【是 】-【终端执行其二进制文件   】
【16 】-【欧陆词典            】-【all       】-【是 】-【是 】-【   】-【                       】
【17 】-【Blocs               】-【all       】-【是 】-【是 】-【   】-【                       】
【18 】-【PlistEdit Pro       】-【all       】-【是 】-【是 】-【   】-【                       】
【19 】-【Downie 4            】-【all       】-【是 】-【是 】-【   】-【                       】
【20 】-【Typora              】-【all       】-【是 】-【是 】-【   】-【                       】
【21 】-【Stash               】-【2.6.2     】-【是 】-【   】-【   】-【                       】
【22 】-【App Cleaner         】-【8.3.1     】-【是 】-【   】-【   】-【                       】
【23 】-【Hype4               】-【all       】-【是 】-【是 】-【是 】-【                       】
【24 】-【Infuse              】-【all       】-【是 】-【是 】-【是 】-【                       】
【25 】-【Kaleidoscope        】-【all       】-【是 】-【是 】-【   】-【                       】
【26 】-【Pixelmator Pro Trial】-【all       】-【是 】-【是 】-【   】-【                       】
【27 】-【Proxyman            】-【5.2.0     】-【是 】-【   】-【   】-【                       】
【28 】-【ServerCat           】-【1.12      】-【是 】-【   】-【是 】-【                       】
【29 】-【Core Tunnel         】-【all       】-【是 】-【是 】-【是 】-【                       】
【30 】-【Navicat Premium     】-【all       】-【是 】-【是 】-【是 】-【借鉴 Qiuchenly         】
【31 】-【Permute 3           】-【all       】-【是 】-【是 】-【   】-【                       】
【32 】-【Eon                 】-【all       】-【是 】-【是 】-【   】-【                       】
【33 】-【UctoX 2             】-【all       】-【是 】-【是 】-【   】-【                       】
【34 】-【Rottenwood          】-【all       】-【是 】-【是 】-【   】-【                       】
【35 】-【Judo                】-【all       】-【是 】-【是 】-【是 】-【免登录 有几个功能不能用】
【36 】-【Querious            】-【all       】-【是 】-【是 】-【   】-【                       】
【37 】-【ForkLift            】-【all       】-【是 】-【是 】-【   】-【                       】
【38 】-【CleanMyMac-MAS      】-【all       】-【是 】-【是 】-【是 】-【不包括状态栏按钮       】
【39 】-【Reveal              】-【49 (20463)】-【是 】-【   】-【   】-【                       】
输入支持的app序号 输入q退出或按下control+c:
36
Error: 依赖文件处理出错
```

**Comment by NKU915** [comment]
@TrialMacApp 我又重新安装Querious，并用下面命令执行命令：
```
sudo ./TrialMacApp
```
还是不成功，但是提示不同错误。启动querious后的界面还是跟前面一样：https://github.com/marlkiller/dylib_dobby_hook/issues/19#issuecomment-2283056449
```
【34 】-【Rottenwood          】-【all       】-【是 】-【是 】-【   】-【                       】
【35 】-【Judo                】-【all       】-【是 】-【是 】-【是 】-【免登录 有几个功能不能用】
【36 】-【Querious            】-【all       】-【是 】-【是 】-【   】-【                       】
【37 】-【ForkLift            】-【all       】-【是 】-【是 】-【   】-【                       】
【38 】-【CleanMyMac-MAS      】-【all       】-【是 】-【是 】-【是 】-【不包括状态栏按钮       】
【39 】-【Reveal              】-【49 (20463)】-【是 】-【   】-【   】-【                       】
输入支持的app序号 输入q退出或按下control+c:
36
注入失败
【Querious】xattr完成
【Querious】签名完成
输入支持的app序号 输入q退出或按下control+c:
```

**Comment by TrialMacApp** [comment]
> @TrialMacApp 我又重新安装Querious，并用下面命令执行命令：
> 
> ```
> sudo ./TrialMacApp
> ```
> 
> 还是不成功，但是提示不同错误。启动querious后的界面还是跟前面一样：[#19 (comment)](https://github.com/marlkiller/dylib_dobby_hook/issues/19#issuecomment-2283056449)
> 
> ```
> 【34 】-【Rottenwood          】-【all       】-【是 】-【是 】-【   】-【                       】
> 【35 】-【Judo                】-【all       】-【是 】-【是 】-【是 】-【免登录 有几个功能不能用】
> 【36 】-【Querious            】-【all       】-【是 】-【是 】-【   】-【                       】
> 【37 】-【ForkLift            】-【all       】-【是 】-【是 】-【   】-【                       】
> 【38 】-【CleanMyMac-MAS      】-【all       】-【是 】-【是 】-【是 】-【不包括状态栏按钮       】
> 【39 】-【Reveal              】-【49 (20463)】-【是 】-【   】-【   】-【                       】
> 输入支持的app序号 输入q退出或按下control+c:
> 36
> 注入失败
> 【Querious】xattr完成
> 【Querious】签名完成
> 输入支持的app序号 输入q退出或按下control+c:
> ```

那应该是注入器的问题了，拉一下最新的代码。

**Comment by marlkiller** [comment]
这个 db 客户端 感觉很一般啊, 为何如此执着

**Comment by TrialMacApp** [comment]
> 这个 db 客户端 感觉很一般啊, 为何如此执着

因为是原生的吧，类似Sequal Ace

**Comment by NKU915** [comment]
> 这个 db 客户端 感觉很一般啊, 为何如此执着

倒不是的，既然 @TrialMacApp 热心提供指引，我只是如何的把实际使用情况反馈给他。每次我提出问题，他都热心解决，那我也不能停止，:-) 
其实非常感谢各位技术狂热大脑！

**Comment by NKU915** [comment]
> > 这个 db 客户端 感觉很一般啊, 为何如此执着
> 
> 因为是原生的吧，类似Sequal Ace

是原生APP，只是觉得UI很不错。其实它支持的数据库有限，主要是Mysql，刚刚才支持sqlite，接下来应该会支持PG
