### ISSUE TITLE
關於libdobby.dylib編譯

### ISSUE THREAD

**Issue by oilrich25** [marlkiller/dylib_dobby_hook#2]
想請教一個問題，請問如何將libdobby項目編譯成dylib？
我通過官方編譯得出的是.a文件，但我想編譯成dylib。目前平台為macOS

您能否詳細告知如何編譯出dylib的詳細過程？ 萬分感恩！

```
git clone https://github.com/wangyinz/Dobby.git --depth=1
python3 scripts/platform_builder.py --platform=macos --arch=all 
```

**Comment by marlkiller** [comment]
git clone https://github.com/wangyinz/Dobby.git --depth=1
python3 scripts/platform_builder.py --platform=macos --arch=all 
执行完后, 生成了以下文件 (你只生成了 .a ,应该是环境问题吧,检查下 控制台的日志信息):

<img width="469" alt="image" src="https://github.com/marlkiller/dylib_dobby_hook/assets/25897113/c70c5c0d-b5c7-43ac-8e16-820d62b38d3f">

**Comment by oilrich25** [comment]
> git clone https://github.com/jmpews/Dobby --depth=1
> 
> python3 scripts/platform_builder.py --platform=macos --arch=all 
> 
> 执行完后, 生成了以下文件 (你只生成了 .a ,应该是环境问题吧,检查下 控制台的日志信息):
> 
> 
> 
> <img width="469" alt="image" src="https://github.com/marlkiller/dylib_dobby_hook/assets/25897113/c70c5c0d-b5c7-43ac-8e16-820d62b38d3f">
> 
> 

感謝🙏
