### ISSUE TITLE
TablePlus Version 6.0.8 (562) auto_hack后无法打开->奔溃

### ISSUE THREAD

**Issue by hsingll** [marlkiller/dylib_dobby_hook#20]
Intel芯片 MBP
系统10.15.7 (19H2026)
TablePlus Version 6.0.8 (562)

auto_hack：
<img width="641" alt="Snipaste_2024-06-28_15-07-05" src="https://github.com/marlkiller/dylib_dobby_hook/assets/26346635/8bb20eac-8bcd-48cb-849c-2ece2660a382">

奔溃日志（超出comment长度了，转为附件）：
[TablePlus_2024-06-28-151553_Macintosh.txt](https://github.com/user-attachments/files/16025733/TablePlus_2024-06-28-151553_Macintosh.txt)

**Comment by marlkiller** [comment]
系统版本 版本太老, 可能还会有其他兼容问题..
