### ISSUE TITLE
fail crack

### ISSUE THREAD

**Issue by leonfrer** [marlkiller/dylib_dobby_hook#21]
无法破解，显示如下错误
![CleanShot 2024-06-30 at 22 55 47@2x](https://github.com/marlkiller/dylib_dobby_hook/assets/51883574/c8ef6935-d4b9-480f-b49c-15da2b1bfe49)

**Comment by leonfrer** [comment]
m1 pro

**Comment by marlkiller** [comment]
软件版本以及奔溃日志贴一下

**Comment by leonfrer** [comment]
![CleanShot 2024-07-01 at 09 06 51@2x](https://github.com/marlkiller/dylib_dobby_hook/assets/51883574/1fc8c58c-57cc-4ceb-a220-532480f0d587)

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Proxyman [51265]
Path:                  /Applications/Proxyman.app/Contents/MacOS/Proxyman
Identifier:            com.proxyman.NSProxy
Version:               5.5.0 (50500)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-07-01 09:06:03.2860 +0800
OS Version:            macOS 14.5 (23F79)
Report Version:        12
Anonymous UUID:        41DB3076-216E-05A3-4D52-D3E6ECB81E4E

Sleep/Wake UUID:       00293510-EB0A-4D80-BA4E-7640660F3A5F

Time Awake Since Boot: 890000 seconds
Time Since Wake:       963 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @loader_path/../Frameworks/HexFiend.framework/Versions/A/HexFiend
Referenced from: <76A2C36A-3C34-3D8A-BBDA-CE82F80E0E39> /Applications/Proxyman.app/Contents/MacOS/Proxyman
Reason: tried: '/Applications/Proxyman.app/Contents/MacOS/../Frameworks/HexFiend.framework/Versions/A/HexFiend' (code signature in <1B9C64E6-31B9-34E0-9402-50DA49C1ADF7> '/Applications/Proxyman.app/Contents/Frameworks/HexFiend.framework/Versions/A/HexFiend' not valid for use in process: Trying to load an unsigned library)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x1944c5a50 __abort_with_payload + 8
1   dyld                          	       0x1944d0628 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x1944d065c abort_with_payload + 16
3   dyld                          	       0x1944626b0 dyld4::halt(char const*, dyld4::StructuredError const*) + 304
4   dyld                          	       0x19445f258 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3888
5   dyld                          	       0x19445dedc start + 1844


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016bd5a910   x3: 0x0000000000000089
    x4: 0x000000016bd5a510   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x000000016bd5a481  x10: 0x000000000000000a  x11: 0x0000000000000000
   x12: 0x0000000000000035  x13: 0x1000000000000000  x14: 0x0000000000000004  x15: 0x0000000000008000
   x16: 0x0000000000000209  x17: 0x000000019445b37c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016bd5a510  x21: 0x0000000000000089  x22: 0x000000016bd5a910  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x0000000000000001  x26: 0x000000016bd5b2d8  x27: 0x0000000000000101
   x28: 0x000000016bd5b398   fp: 0x000000016bd5a4e0   lr: 0x00000001944d0628
    sp: 0x000000016bd5a4a0   pc: 0x00000001944c5a50 cpsr: 0x80001000
   far: 0x0000000000000000  esr: 0x56000080  Address size fault

Binary Images:
       0x104ba0000 -        0x104bf7fff org.cocoapods.Alamofire (4.9.1) <66c30b83-9234-3ade-ab92-0acefce03072> /Applications/Proxyman.app/Contents/Frameworks/Alamofire.framework/Versions/A/Alamofire
       0x104a5c000 -        0x104a77fff org.cocoapods.Moya (13.0.1) <5cdf5076-327f-341b-adb0-0d3e07de65e5> /Applications/Proxyman.app/Contents/Frameworks/Moya.framework/Versions/A/Moya
       0x1049f4000 -        0x1049fbfff org.cocoapods.Result (4.1.0) <3a41622c-4c08-34fd-b3a0-c0242b222439> /Applications/Proxyman.app/Contents/Frameworks/Result.framework/Versions/A/Result
       0x104ab4000 -        0x104afbfff org.sparkle-project.Sparkle (1.27.0) <1b8093b5-826e-344b-9aa2-62ee13fa4205> /Applications/Proxyman.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x1049ac000 -        0x1049bbfff org.cocoapods.SwiftyXMLParser (5.4.0) <a8409140-e5c9-3b4d-aeba-4541ac8bb51f> /Applications/Proxyman.app/Contents/Frameworks/SwiftyXMLParser.framework/Versions/A/SwiftyXMLParser
       0x104a18000 -        0x104a23fff org.cocoapods.WebPKit (1.0.0) <62387c7d-8a75-301e-bd65-503d0a70cbce> /Applications/Proxyman.app/Contents/Frameworks/WebPKit.framework/Versions/A/WebPKit
       0x104df8000 -        0x104e4bfff org.cocoapods.libwebp (1.3.2) <6141b140-fcec-3e4f-98f3-f4d5d411fe40> /Applications/Proxyman.app/Contents/Frameworks/libwebp.framework/Versions/A/libwebp
       0x104e98000 -        0x104ec3fff org.cocoapods.macOSThemeKit (1.4.0) <89ff0752-04d9-3972-8749-65247eeb3694> /Applications/Proxyman.app/Contents/Frameworks/macOSThemeKit.framework/Versions/A/macOSThemeKit
       0x106ff4000 -        0x107c3bfff com.nsproxy.ProxymanCore (3.11.0) <a9053545-abe2-3e81-bbb8-9adbe7b73841> /Applications/Proxyman.app/Contents/Frameworks/ProxymanCore.framework/Versions/A/ProxymanCore
       0x1040a4000 -        0x104453fff com.proxyman.NSProxy (5.5.0) <76a2c36a-3c34-3d8a-bbda-ce82f80e0e39> /Applications/Proxyman.app/Contents/MacOS/Proxyman
       0x194458000 -        0x1944e0a17 dyld (*) <37bbc384-0755-31c7-a808-0ed49e44dd8e> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=555.8M resident=0K(0%) swapped_out_or_unallocated=555.8M(100%)
Writable regions: Total=12.8M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=12.8M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__DATA                            1563K       15 
__DATA_CONST                       807K       11 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       538.0M       11 
__TEXT                            17.9M       11 
dyld private memory               4384K        4 
===========                     =======  ======= 
TOTAL                            626.5M       56 



-----------
Full Report
-----------

{"app_name":"Proxyman","timestamp":"2024-07-01 09:06:03.00 +0800","app_version":"5.5.0","slice_uuid":"76a2c36a-3c34-3d8a-bbda-ce82f80e0e39","build_version":"50500","platform":1,"bundleID":"com.proxyman.NSProxy","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.5 (23F79)","roots_installed":0,"name":"Proxyman","incident_id":"25A1C66F-9536-401E-B1EF-F454EADDE828"}
{
  "uptime" : 890000,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,1",
  "coalitionID" : 81830,
  "osVersion" : {
    "train" : "macOS 14.5",
    "build" : "23F79",
    "releaseType" : "User"
  },
  "captureTime" : "2024-07-01 09:06:03.2860 +0800",
  "codeSigningMonitor" : 1,
  "incident" : "25A1C66F-9536-401E-B1EF-F454EADDE828",
  "pid" : 51265,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-07-01 09:06:00.2480 +0800",
  "procStartAbsTime" : 21597374492282,
  "procExitAbsTime" : 21597447353447,
  "procName" : "Proxyman",
  "procPath" : "\/Applications\/Proxyman.app\/Contents\/MacOS\/Proxyman",
  "bundleInfo" : {"CFBundleShortVersionString":"5.5.0","CFBundleVersion":"50500","CFBundleIdentifier":"com.proxyman.NSProxy"},
  "storeInfo" : {"deviceIdentifierForVendor":"51DEE110-B243-5941-8A3D-F0E1ACE16572","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.proxyman.NSProxy",
  "crashReporterKey" : "41DB3076-216E-05A3-4D52-D3E6ECB81E4E",
  "codeSigningID" : "com.proxyman.NSProxy",
  "codeSigningTeamID" : "3X57WP8E8V",
  "codeSigningFlags" : 570503953,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"1AAAABABAAAYAQAAIAEAACgBAAAwAQAAOAEAAFQBAAAwQYDSARAA1A==","atPC":"AwEAVH8jA9X9e7+p\/QMAkQpV\/pe\/AwCR\/XvBqP8PX9bAA1\/WEC2A0g=="},
  "wakeTime" : 963,
  "sleepWakeUUID" : "00293510-EB0A-4D80-BA4E-7640660F3A5F",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @loader_path\/..\/Frameworks\/HexFiend.framework\/Versions\/A\/HexFiend","Referenced from: <76A2C36A-3C34-3D8A-BBDA-CE82F80E0E39> \/Applications\/Proxyman.app\/Contents\/MacOS\/Proxyman","Reason: tried: '\/Applications\/Proxyman.app\/Contents\/MacOS\/..\/Frameworks\/HexFiend.framework\/Versions\/A\/HexFiend' (code signature in <1B9C64E6-31B9-34E0-9402-50DA49C1ADF7> '\/Applications\/Proxyman.app\/Contents\/Frameworks\/HexFiend.framework\/Versions\/A\/HexFiend' not valid for use in process: Trying to load an unsigned library)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":10766014,"threadState":{"x":[{"value":6},{"value":1},{"value":6104131856},{"value":137},{"value":6104130832},{"value":0},{"value":0},{"value":0},{"value":32},{"value":6104130689},{"value":10},{"value":0},{"value":53},{"value":1152921504606846976},{"value":4},{"value":32768},{"value":521},{"value":6782563196,"symbolLocation":416,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6104130832},{"value":137},{"value":6104131856},{"value":1},{"value":6},{"value":1},{"value":6104134360},{"value":257},{"value":6104134552}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6783043112},"cpsr":{"value":2147487744},"fp":{"value":6104130784},"sp":{"value":6104130720},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6782999120,"matchesCrashFrame":1},"far":{"value":0}},"frames":[{"imageOffset":449104,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":10},{"imageOffset":493096,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":10},{"imageOffset":493148,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":10},{"imageOffset":42672,"symbol":"dyld4::halt(char const*, dyld4::StructuredError const*)","symbolLocation":304,"imageIndex":10},{"imageOffset":29272,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3888,"imageIndex":10},{"imageOffset":24284,"symbol":"start","symbolLocation":1844,"imageIndex":10}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4374265856,
    "CFBundleShortVersionString" : "4.9.1",
    "CFBundleIdentifier" : "org.cocoapods.Alamofire",
    "size" : 360448,
    "uuid" : "66c30b83-9234-3ade-ab92-0acefce03072",
    "path" : "\/Applications\/Proxyman.app\/Contents\/Frameworks\/Alamofire.framework\/Versions\/A\/Alamofire",
    "name" : "Alamofire",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4372938752,
    "CFBundleShortVersionString" : "13.0.1",
    "CFBundleIdentifier" : "org.cocoapods.Moya",
    "size" : 114688,
    "uuid" : "5cdf5076-327f-341b-adb0-0d3e07de65e5",
    "path" : "\/Applications\/Proxyman.app\/Contents\/Frameworks\/Moya.framework\/Versions\/A\/Moya",
    "name" : "Moya",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4372512768,
    "CFBundleShortVersionString" : "4.1.0",
    "CFBundleIdentifier" : "org.cocoapods.Result",
    "size" : 32768,
    "uuid" : "3a41622c-4c08-34fd-b3a0-c0242b222439",
    "path" : "\/Applications\/Proxyman.app\/Contents\/Frameworks\/Result.framework\/Versions\/A\/Result",
    "name" : "Result",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4373299200,
    "CFBundleShortVersionString" : "1.27.0",
    "CFBundleIdentifier" : "org.sparkle-project.Sparkle",
    "size" : 294912,
    "uuid" : "1b8093b5-826e-344b-9aa2-62ee13fa4205",
    "path" : "\/Applications\/Proxyman.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/A\/Sparkle",
    "name" : "Sparkle",
    "CFBundleVersion" : "1.102"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4372217856,
    "CFBundleShortVersionString" : "5.4.0",
    "CFBundleIdentifier" : "org.cocoapods.SwiftyXMLParser",
    "size" : 65536,
    "uuid" : "a8409140-e5c9-3b4d-aeba-4541ac8bb51f",
    "path" : "\/Applications\/Proxyman.app\/Contents\/Frameworks\/SwiftyXMLParser.framework\/Versions\/A\/SwiftyXMLParser",
    "name" : "SwiftyXMLParser",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4372660224,
    "CFBundleShortVersionString" : "1.0.0",
    "CFBundleIdentifier" : "org.cocoapods.WebPKit",
    "size" : 49152,
    "uuid" : "62387c7d-8a75-301e-bd65-503d0a70cbce",
    "path" : "\/Applications\/Proxyman.app\/Contents\/Frameworks\/WebPKit.framework\/Versions\/A\/WebPKit",
    "name" : "WebPKit",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4376723456,
    "CFBundleShortVersionString" : "1.3.2",
    "CFBundleIdentifier" : "org.cocoapods.libwebp",
    "size" : 344064,
    "uuid" : "6141b140-fcec-3e4f-98f3-f4d5d411fe40",
    "path" : "\/Applications\/Proxyman.app\/Contents\/Frameworks\/libwebp.framework\/Versions\/A\/libwebp",
    "name" : "libwebp",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4377378816,
    "CFBundleShortVersionString" : "1.4.0",
    "CFBundleIdentifier" : "org.cocoapods.macOSThemeKit",
    "size" : 180224,
    "uuid" : "89ff0752-04d9-3972-8749-65247eeb3694",
    "path" : "\/Applications\/Proxyman.app\/Contents\/Frameworks\/macOSThemeKit.framework\/Versions\/A\/macOSThemeKit",
    "name" : "macOSThemeKit",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4412358656,
    "CFBundleShortVersionString" : "3.11.0",
    "CFBundleIdentifier" : "com.nsproxy.ProxymanCore",
    "size" : 12877824,
    "uuid" : "a9053545-abe2-3e81-bbb8-9adbe7b73841",
    "path" : "\/Applications\/Proxyman.app\/Contents\/Frameworks\/ProxymanCore.framework\/Versions\/A\/ProxymanCore",
    "name" : "ProxymanCore",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4362747904,
    "CFBundleShortVersionString" : "5.5.0",
    "CFBundleIdentifier" : "com.proxyman.NSProxy",
    "size" : 3866624,
    "uuid" : "76a2c36a-3c34-3d8a-bbda-ce82f80e0e39",
    "path" : "\/Applications\/Proxyman.app\/Contents\/MacOS\/Proxyman",
    "name" : "Proxyman",
    "CFBundleVersion" : "50500"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6782550016,
    "size" : 559640,
    "uuid" : "37bbc384-0755-31c7-a808-0ed49e44dd8e",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6781796352,
  "size" : 4220698624,
  "uuid" : "3406ad1b-2469-30eb-9863-5dce861e6dea"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=555.8M resident=0K(0%) swapped_out_or_unallocated=555.8M(100%)\nWritable regions: Total=12.8M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=12.8M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__DATA                            1563K       15 \n__DATA_CONST                       807K       11 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       538.0M       11 \n__TEXT                            17.9M       11 \ndyld private memory               4384K        4 \n===========                     =======  ======= \nTOTAL                            626.5M       56 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "22b1fb8df4101d1fad421dce64767269b67d0179",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6410af69ed1e1e7ab93ed169",
      "factorPackIds" : {

      },
      "deploymentId" : 240000011
    },
    {
      "rolloutId" : "652eff3d1bce5442b8d753c9",
      "factorPackIds" : {

      },
      "deploymentId" : 240000009
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "45f4e2a5-551b-4bc2-a2dc-19c244dda8f8",
      "experimentId" : "6643969b3099cf28e049862f",
      "deploymentId" : 400000002
    },
    {
      "treatmentId" : "c47ab4cc-c9c3-4b5d-a87c-e2433ce02597",
      "experimentId" : "6639bc6ba73d460582162323",
      "deploymentId" : 400000006
    }
  ]
}
}

Model: MacBookPro18,1, BootROM 10151.121.1, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Samsung
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Apr  4 2024 20:37:43 version 20.103.14.0.8.7.174 FWID 01-95f1e684
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by marlkiller** [comment]
当前只支持 5.2 版本, 后面更新太频 很久没维护了
