### ISSUE TITLE
Support for more Apps

### ISSUE THREAD

**Issue by tanu360** [marlkiller/dylib_dobby_hook#24]
1. Nektony App Cleaner & Uninstaller : https://download.nektony.com/download/app-cleaner-uninstaller/app-cleaner-uninstaller.dmg
2. Cleanshot X : https://cleanshot.com

Both of these are widely used and static patching of these apps are so tiresome as they have helper module which not works well unless we patch the sig in all files. I hope you can try dynamic patching these 2 apps. It would be really great.

Thank you so much.

**Comment by ethaniel86** [comment]
and Termius

**Comment by NKU915** [comment]
> and Termius

https://macked.app/termius-crack.html
