### ISSUE TITLE
can you add a hook for BetterMouse ?

### ISSUE THREAD

**Issue by laofun** [marlkiller/dylib_dobby_hook#27]
Hi,

I have been trying to hook the Paddle.framework with BetterMouse, but it only works for a short period before I receive a Trial expired notification. Could you please help me resolve this issue?

Thank you.

website: [https://better-mouse.com/](url)

**Comment by marlkiller** [comment]
The Framework directory seems a little strange;
But you can also try to inject the main program;
The code can be referred to: ` MovistProHack.m`
```
 /Applications/BetterMouse.app/Contents/MacOS/BetterMouse;
```
<img width="835" alt="image" src="https://github.com/user-attachments/assets/1935ede4-97d9-4f30-a102-e21d86c9b4a1">
