### ISSUE TITLE
Build以后没有release产物

### ISSUE THREAD

**Issue by drainlin** [marlkiller/dylib_dobby_hook#3]
原样DEMO下载后Build,release文件下无更新的产物生成
请问一下如何得到产物呢?
另外run script会失败，permission denied

**Comment by marlkiller** [comment]
1. Xcode > Product > Show Build Folder in Finder
2. sudo sh hack.sh

**Comment by drainlin** [comment]
> 1. Xcode > Product > Show Build Folder in Finder
> 2. sudo sh hack.sh

谢谢
我发现出现此问题是因为我从Mac App Store下载的
从第三方下载的无权限问题

**Comment by drainlin** [comment]
> > 1. Xcode > Product > Show Build Folder in Finder
> > 2. sudo sh hack.sh
> 
> 谢谢 我发现出现此问题是因为我从Mac App Store下载的 从第三方下载的无权限问题

解决方法是：
需要手动进行注入，把可执行文件拖出来注入后再放回去即可解决。
感谢作者的模板，非常方便！

**Comment by marlkiller** [comment]
噢噢, 我一般不去 AppStore 下载 APP

**Comment by marlkiller** [comment]
特意试了下, AppStore 下的的 , 要改一下 Run Script
root_password="xxxxxx"
......
echo "$root_password" | sudo -S cp "$app_executable_path" "$app_executable_backup_path"
.....
