### ISSUE TITLE
iStat Menus weather issue

### ISSUE THREAD

**Issue by RegulusMac** [marlkiller/dylib_dobby_hook#38]
I found another issue in iStat Menus
Weather data in StatusMenu shows:

**Your weather access has expired**

Weather data with frequency and expire date in main app is working.

**Comment by RegulusMac** [comment]
Some additional information from the statesmenu weather display.
I managed to get the info back after a clean install and using the trial
version first.
Then I used iStat Menus with injection and it worked for 1 hour.
Then I got the message from above post back.
Hope that helps.

**Comment by marlkiller** [comment]
The weather data is returned by the API, and the server verifies the license; 
So this issue shouldn't be fixed.

```



/Applications/iStat Menus.app/Contents/Resources/Components.bundle/Contents/Resources/iStat Menus Menubar.app/Contents/Frameworks/BBRWeatherKit.framework/Versions/A/BBRWeatherKit


https://weather.istatmenus.app/istatmenus/v3/weather/

POST /istatmenus/v3/weather/ HTTP/1.1
Host: weather.istatmenus.app
Content-Type: application/x-www-form-urlencoded
Connection: keep-alive
Accept: */*
User-Agent: iStat%20Menus%20Menubar/2231 CFNetwork/1568.200.51 Darwin/24.1.0
Accept-Language: zh-CN,zh-Hans;q=0.9
Content-Length: 252
Accept-Encoding: gzip, deflate, br


{"start":0,"end":0,"frequency":60,"devices":0,"paid":"1","subscription-expired":1,"error":{"code":"expired"}}



```
