### ISSUE TITLE
TablePlus无法在原生状态打开

### ISSUE THREAD

**Issue by drainlin** [marlkiller/dylib_dobby_hook#4]
机型M2 MacBook Air
下载安装官网版TablePlus后执行build
原生Arm版无法运行，提示应用程序“TablePlus”无法打开。
打开转译可以完美运行，请问这个是什么原因导致的
不仅是TablePlus，注入到其他程序，也是只有开启rosetta后才能打开，arm下无法打开
<img width="273" alt="截屏2024-01-27 13 56 18" src="https://github.com/marlkiller/dylib_dobby_hook/assets/70575379/ae94c22f-9cf4-4426-8a61-8c81e8af7a18">
<img width="342" alt="截屏2024-01-27 13 55 52" src="https://github.com/marlkiller/dylib_dobby_hook/assets/70575379/149330a8-3757-4ebf-9927-b2ffe4c910b8">

**Comment by marlkiller** [comment]
arm 版的 dylib 需要在 arm 环境(Mac m1 )下 build, 注意 Build 的时候不要选择 Rosetta 模式.
```
lipo -info libdylib_dobby_hook.dylib 
Architectures in the fat file: libdylib_dobby_hook.dylib are: x86_64 arm64 
```
同时 构建后的 dylib 可以在原始 arm 下跑, 也可以在 原生 x86下跑, 但是目前不支持 在 arm下 用 rosetta 跑.
