### ISSUE TITLE
Cleanshot X

### ISSUE THREAD

**Issue by tanu360** [marlkiller/dylib_dobby_hook#40]
Your new changes broke the Cleanshot. It can not be activated now.

**Comment by marlkiller** [comment]
[TODO](https://github.com/Antibioticss/tinyhook/issues/7)

**Comment by marlkiller** [comment]
closed: https://github.com/marlkiller/dylib_dobby_hook/commit/fa5e0d0f55c35a1a2272986cf515b7270385d27d
