### ISSUE TITLE
大佬 请教一个 M2 电脑  hook 崩溃的问题

### ISSUE THREAD

**Issue by CoderShmily** [marlkiller/dylib_dobby_hook#41]
![image](https://github.com/user-attachments/assets/1db7d6e6-e29b-4613-8c04-c9a020639819)
![image](https://github.com/user-attachments/assets/2068f558-c916-482c-9438-f3ed8fe8d3c3)
大佬 我的 m2 电脑  hook 的一个mac app 的https://github.com/520coding/confuse/blob/master/confuse.dmg  正常的方法名是没有问题的，但是对于 sub 开头的方法，无论是使用DobbyHook 还是 tiny_hook  在调用原方法的时候 都会崩溃，能帮忙指导一下吗 是代码问题 还是什么问题？

**Comment by marlkiller** [comment]
检查下 Memutil 获取到的 函数地址是否正确,
lldb :
dis -a sub_xxx_addr
检查下 hook 中获取的俩个参数是否跟正常参数匹配, 注意参数类型

**Comment by CoderShmily** [comment]
> 检查下 Memutil 获取到的 函数地址是否正确, lldb : dis -a sub_xxx_addr 检查下 hook 中获取的俩个参数是否跟正常参数匹配, 注意参数类型

![image](https://github.com/user-attachments/assets/a6319941-2cd1-4335-9240-3b9de4eb8bcb)
![image](https://github.com/user-attachments/assets/03443e00-731f-4597-9684-134cfa4e4be7)
看着是一致的

**Comment by CoderShmily** [comment]
谢谢大佬 打印出来的类型 一个 block  一个 nsstring 没想到 IDA 这地方误差这么大，谢谢啦😄
(__NSMallocBlock__ *) arg0 = 0x00006000023d18c0
(__NSCFString *) arg1 = 0x0000600002178630 @"{\"code\":200,\"message\":\"\",\"data\":[]}"
