### ISSUE TITLE
编译出来的lib能否用于ios注入？

### ISSUE THREAD

**Issue by LeeeMooo** [marlkiller/dylib_dobby_hook#5]
不熟悉ios开发，请问可以注入ios吗？

还是说需要重新编译dobbyhook再新建一个xcode for ios library?

------

贡献一个 [Paste 4.1.3](https://apps.apple.com/cn/app/paste-clipboard-manager/id967805235)，arm可用

[paste.zip](https://github.com/marlkiller/dylib_dobby_hook/files/14079063/paste.zip)

注入脚本要改一下，有些app没有Frameworks文件夹

**Comment by marlkiller** [comment]
不同的操作系统依赖的dobby dylib 也是不同的，暂时还没想到怎么样适配。

---
这个 patch 可以提 pr 吗？ 我有空也会看看
