### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by suhang12332** [marlkiller/dylib_dobby_hook#7]
<img width="782" alt="image" src="https://github.com/marlkiller/dylib_dobby_hook/assets/48873455/22adb92b-3cb2-44c3-9b54-aa0cd8b80395">
 
系统 macos14。m1 pro

**Comment by marlkiller** [comment]
我这边没复现啊
<img width="243" alt="image" src="https://github.com/marlkiller/dylib_dobby_hook/assets/25897113/81eed00f-7adf-4e84-9b9c-5b2ac66cfad2">

<img width="688" alt="image" src="https://github.com/marlkiller/dylib_dobby_hook/assets/25897113/c2acbcc6-bf90-43a1-a48c-fbf8de896e9e">

**Comment by chaclee** [comment]
Terminal exec:
`softwareupdate --install-rosetta`
