### ISSUE TITLE
使用writeMachineCodeString修改内存中的机器码奔溃问题

### ISSUE THREAD

**Issue by gyc-12** [marlkiller/dylib_dobby_hook#8]
<img width="1567" alt="image" src="https://github.com/marlkiller/dylib_dobby_hook/assets/74996459/a5f3b45e-9eed-4f89-9173-1921305e726b">
<img width="1956" alt="image" src="https://github.com/marlkiller/dylib_dobby_hook/assets/74996459/bcd95e8b-3b0e-483b-8488-9d34d056ccbb">
大佬，请教个问题，我想把000000010011970e        je        loc_10011972c  修改为----->>        jne        loc_10011972c
对应机器码是74改成75，用的大佬的项目中的writeMachineCodeString方法，为啥注入后程序奔溃呢，奔溃日志如图，代码拉取的最新main分支

**Comment by marlkiller** [comment]
这个 write的方法我自己还没用过 .., 可能是长度参数没适配好; 试试下面这段;
`
#import "dobby.h"

NSLog(@">>>>>> Before %s",[MemoryUtils readMachineCodeStringAtAddress:0x10011970e length:8].UTF8String);
uint8_t ret1Day[1] = {0x75  };
DobbyCodePatch((void *)0x10011970e, ret1Day,1);
NSLog(@">>>>>> After %s",[MemoryUtils readMachineCodeStringAtAddress:0x10011970e length:8].UTF8String);
`

**Comment by gyc-12** [comment]
> 这个 write的方法我自己还没用过 .., 可能是长度参数没适配好; 试试下面这段; ` #import "dobby.h"
> 
> NSLog(@">>>>>> Before %s",[MemoryUtils readMachineCodeStringAtAddress:0x10011970e length:8].UTF8String); uint8_t ret1Day[1] = {0x75 }; DobbyCodePatch((void *)0x10011970e, ret1Day,1); NSLog(@">>>>>> After %s",[MemoryUtils readMachineCodeStringAtAddress:0x10011970e length:8].UTF8String); `
大佬太强了！秒杀。

**Comment by marlkiller** [comment]
有空看看 writeMachineCodeString 的 bug 吧 ; 欢迎 pr。😄
